// ===== 夜桜の夢 — Site Content Database =====
// Generated: 2026/3/20 上午12:41:09

const siteData = {
  "about": {
    "photos": [
      "https://i.ibb.co/d0jHqV4k/yuyu-1.jpg",
      "https://i.ibb.co/mFgWKSxj/S-28147831-0.jpg",
      "https://i.ibb.co/Gv90mv5x/photo-2025-06-03-16-32-54.jpg",
      "https://i.ibb.co/bTkVcn3/S-28147830-0.jpg"
    ],
    "p1Ja": "はじめまして、ゆうゆうと申します。台湾出身です。昔から日本の文化や礼儀作法に憧れていて、卒業を機に、ついに夢だった日本での生活をスタートさせました。",
    "p1Zh": "大家好～我是悠悠，來自台灣！從小就被日本的文化與禮儀深深吸引，畢業後終於實現夢想來到日本生活。",
    "p1En": "Hello! I'm Yuuyuu from Taiwan. I've always been fascinated by Japanese culture and etiquette. After graduation, I finally made my dream come true and started living in Japan.",
    "p2Ja": "友人の紹介でこのお仕事を始めましたが、日本語はまだ勉強中です。翻訳アプリにも助けてもらいながら、一生懸命がんばっています。もし表現に不自然なところがあったら、やさしく教えてくれるとうれしいです。",
    "p2Zh": "目前通過朋友介紹從事這份工作，雖然日語還在努力學習中（暫時需要翻譯軟體幫忙）。如果有任何表達不夠準確的地方，還請大家多多包涵指教～",
    "p2En": "I started this work through a friend's introduction. I'm still learning Japanese (with help from translation apps). If my expression sounds unnatural, please kindly correct me!",
    "moreJa": "もっと見る →",
    "moreZh": "更多介紹 →",
    "moreEn": "Learn more →",
    "linkUrl": "https://t.me/ty556k"
  },
  "girls": [
    {
      "id": 1,
      "name": "アイちゃん",
      "nameZh": "小愛",
      "nameEn": "Ai",
      "height": 161,
      "age": 24,
      "cup": "E",
      "weight": 46,
      "badge": "人気No.1",
      "badgeZh": "人氣No.1",
      "badgeEn": "人気No.1",
      "types": [
        "清楚系",
        "AV経験"
      ],
      "typesZh": [
        "清純型",
        "AV經驗"
      ],
      "typesEn": [
        "Innocent",
        "AV Exp."
      ],
      "image": "https://i.ibb.co/zTK6cRzG/17f2f4e84b7f492c06cf061445a01bf2.jpg",
      "active": true,
      "order": 1,
      "images": [
        "https://i.ibb.co/zTK6cRzG/17f2f4e84b7f492c06cf061445a01bf2.jpg"
      ]
    },
    {
      "id": 2,
      "name": "ミアちゃん",
      "nameZh": "小米亞",
      "nameEn": "Mia",
      "height": 162,
      "age": 25,
      "cup": "D",
      "weight": 47,
      "badge": "NEW",
      "badgeZh": "新人",
      "badgeEn": "NEW",
      "types": [
        "素人系",
        "セクシー系"
      ],
      "typesZh": [
        "素人型",
        "性感型"
      ],
      "typesEn": [
        "Amateur",
        "Sexy"
      ],
      "image": "https://i.ibb.co/pvJB8wDS/18dcf2d6221cd5af79077be6eecfa091.jpg",
      "active": true,
      "order": 2,
      "images": [
        "https://i.ibb.co/pvJB8wDS/18dcf2d6221cd5af79077be6eecfa091.jpg"
      ]
    },
    {
      "id": 3,
      "name": "ユイちゃん",
      "nameZh": "小唯",
      "nameEn": "Yui",
      "height": 160,
      "age": 23,
      "cup": "E",
      "weight": 46,
      "badge": "リピ率高",
      "badgeZh": "回頭客高",
      "badgeEn": "リピ率高",
      "types": [
        "巨乳系"
      ],
      "typesZh": [
        "巨乳型"
      ],
      "typesEn": [
        "Busty"
      ],
      "image": "https://i.ibb.co/Pv8Lcrnr/6197ad6dd36a271ce1386ab0346970b3.jpg",
      "active": true,
      "order": 3,
      "images": [
        "https://i.ibb.co/Pv8Lcrnr/6197ad6dd36a271ce1386ab0346970b3.jpg"
      ]
    },
    {
      "id": 4,
      "name": "なや",
      "nameZh": "菜椰",
      "nameEn": "naya",
      "height": 166,
      "age": 22,
      "cup": "E",
      "weight": 50,
      "badge": "おすすめ",
      "badgeZh": "推薦",
      "badgeEn": "おすすめ",
      "types": [
        "可愛系",
        "清楚系"
      ],
      "typesZh": [
        "可愛型",
        "清純型"
      ],
      "typesEn": [
        "Cute",
        "Innocent"
      ],
      "image": "https://i.ibb.co/hJVZbzGR/S-28147862.jpg",
      "active": true,
      "order": 4,
      "images": [
        "https://i.ibb.co/hJVZbzGR/S-28147862.jpg"
      ]
    },
    {
      "id": 5,
      "name": "ゆうは",
      "nameZh": "優葉",
      "nameEn": "yuuha",
      "height": 165,
      "age": 26,
      "cup": "H",
      "weight": 50,
      "badge": "HOT",
      "badgeZh": "HOT",
      "badgeEn": "HOT",
      "types": [
        "優雅系",
        "高級系",
        "セクシー系"
      ],
      "typesZh": [
        "優雅型",
        "高級型",
        "性感型"
      ],
      "typesEn": [
        "Elegant",
        "Premium",
        "Sexy"
      ],
      "image": "https://i.ibb.co/hJcT8PVj/message-Image-1773668984270.jpg",
      "active": true,
      "order": 5,
      "images": [
        "https://i.ibb.co/hJcT8PVj/message-Image-1773668984270.jpg"
      ]
    },
    {
      "id": 6,
      "name": "らくらく",
      "nameZh": "楽々",
      "nameEn": "rakuraku",
      "height": 160,
      "age": 22,
      "cup": "E",
      "weight": 48,
      "badge": "NEW",
      "badgeZh": "新人",
      "badgeEn": "NEW",
      "types": [
        "巨乳系",
        "素人系"
      ],
      "typesZh": [
        "巨乳型",
        "素人型"
      ],
      "typesEn": [
        "Busty",
        "Amateur"
      ],
      "image": "https://i.ibb.co/jvwgQbsQ/message-Image-1773669115468.jpg",
      "active": true,
      "order": 6,
      "images": [
        "https://i.ibb.co/jvwgQbsQ/message-Image-1773669115468.jpg"
      ]
    }
  ],
  "reviews": [
    {
      "id": 5,
      "titleJa": "毎回のご予約を大切に",
      "titleZh": "每一次安排我都很珍惜",
      "titleEn": "I cherish every arrangement",
      "contentJa": "ハナちゃんは初出勤とのことで、少し緊張していたようだが、それがまた可愛くて。素人感が本当によくて、リピートしたいです。",
      "contentZh": "小花說是初次出勤，看起來有點緊張，但這樣反而更可愛。素人感非常真實，想回訪。",
      "contentEn": "Hana was on her debut, a little nervous which made her even cuter. The amateur feel was very real, want to repeat.",
      "date": "2026.01.28",
      "girlName": "ハナちゃん",
      "rating": 4,
      "featured": true
    },
    {
      "id": 4,
      "titleJa": "いつも信じてくれてありがとう",
      "titleZh": "謝謝你一直信任我安排",
      "titleEn": "Thanks for always trusting my arrangement",
      "contentJa": "ユイちゃんは本当に天使。サービス中ずっとニコニコして、こちらが緊張しても優しくリードしてくれた。お風呂上がりの彼女がとてもきれいで、もう一回やりたいと思った。",
      "contentZh": "唯真的是天使。服務過程中一直微笑，緊張的時候也輕柔地引導。沐浴後的她非常漂亮，讓人想再來一次。",
      "contentEn": "Yui is truly an angel. She smiled throughout and gently led me when nervous. She looked so beautiful after the bath, I wanted to go again.",
      "date": "2026.02.14",
      "girlName": "ユイちゃん",
      "rating": 5,
      "featured": true
    },
    {
      "id": 3,
      "titleJa": "リピーター+1",
      "titleZh": "熟客回流+1",
      "titleEn": "Repeat customer +1",
      "contentJa": "リナとは3回目になりますが、毎回ちゃんと前回のことを覚えていてくれて、本当に嬉しい。サービスも毎回進化している気がして、次回も絶対予約します！",
      "contentZh": "已經是第3次找莉娜了，每次她都記得上次的事，真的很窩心。服務感覺每次都有進步，下次一定還會預約！",
      "contentEn": "3rd time with Rina, she always remembers our previous time. Service keeps getting better, definitely booking again!",
      "date": "2026.02.20",
      "girlName": "リナちゃん",
      "rating": 5,
      "featured": true
    },
    {
      "id": 2,
      "titleJa": "嘿嘿～またお兄ちゃんが虜に～",
      "titleZh": "嘿嘿～又有一位哥哥淪陷啦",
      "titleEn": "Another brother won over~",
      "contentJa": "部屋で待っていた妹は、見た目もスタイルも完璧で、バランスの取れた体型だった。最初に料金を支払ってから一緒にお風呂に入った。締まりの良さと自然な反応が最高で、まさに彼女のような感覚だった。",
      "contentZh": "在房間等我的妹妹，外表和身材都完美，體型很勻稱。先付費後一起入浴。緊實度和自然反應超棒，就像女友般的感覺。",
      "contentEn": "The girl waiting was perfect in looks and style. Paid first then bathed together. Her tightness and natural reactions were amazing, felt like a girlfriend.",
      "date": "2026.03.05",
      "girlName": "ミアちゃん",
      "rating": 5,
      "featured": true
    },
    {
      "id": 1,
      "titleJa": "信じてくれてありがとう、お兄ちゃん💗",
      "titleZh": "感謝哥哥的信任💗",
      "titleEn": "Thank you for trusting me 💗",
      "contentJa": "妹は見た目細いけど、脱いだら意外にエロい体型でビックリ！騎乗位で摇れてる乳の揺れが最高で、こっちはただ見てるだけで我慢できなくなりました…終わった後のアフターサービスも抜かりなく、一緒にシャワーしてくれて、ゆっくり退室できたのが嬉しかったです。",
      "contentZh": "妹妹看起來瘦瘦的，脫了之後意外很有料！騎乘位時乳搖超讚，光看就忍不住了…結束後的售後服務也很周到，一起沖澡、慢慢退房，很開心。",
      "contentEn": "She looked slim but was surprisingly sexy undressed! The bounce in cowgirl was amazing... Aftercare was thorough, shower together and relaxed checkout. Very satisfying.",
      "date": "2026.03.10",
      "girlName": "アイちゃん",
      "rating": 5,
      "featured": true
    }
  ],
  "diary": [
    {
      "id": 50,
      "titleJa": "番号7112",
      "titleZh": "番號7112",
      "titleEn": "Part number 7112",
      "excerpt": "🇯🇵| 店長のおすすめ 長時間割引（交通費込み）",
      "excerptZh": "🇯🇵| 店長推薦 長時間有折扣（包含交通費） ",
      "excerptEn": "Manager's Recommendation: Long-term discounts available (transportation included).",
      "contentJa": "🇯🇵| 店長推薦 長期割引（交通費込み）",
      "contentZh": "🇯🇵| 店長推薦 長時間有折扣（包含交通費） ",
      "contentEn": "🇯🇵| Manager's Recommendation: Long-term discount (transportation fee included)",
      "category": "出勤情報",
      "date": "2026.3.19",
      "thumbnail": "https://i.ibb.co/8LD5BLbN/photo-2025-09-19-12-59-02-2.jpg",
      "image": "https://i.ibb.co/8LD5BLbN/photo-2025-09-19-12-59-02-2.jpg",
      "stats": {
        "height": 160,
        "cup": "D",
        "age": 22,
        "weight": 45
      },
      "published": true
    },
    {
      "id": 51,
      "titleJa": "番号7113",
      "titleZh": "番號7113",
      "titleEn": "No. 7113",
      "excerpt": "店長のおすすめ 長時間割引あり（交通費込み）",
      "excerptZh": "🇯🇵| 店長推薦 長時間有折扣（包含交通費） ",
      "excerptEn": "🇯🇵| Manager's Recommendation: Long-term discount (transportation included)",
      "contentJa": "店長のおすすめ 長時間割引（交通費込み）",
      "contentZh": "🇯🇵| 店長推薦 長時間有折扣（包含交通費） ",
      "contentEn": "Manager's Recommendation: Long-term discount (transportation fee included)",
      "category": "出勤情報",
      "date": "2026.3.19",
      "thumbnail": "https://i.ibb.co/99tc0tnG/photo-2025-09-19-13-01-25-2.jpg",
      "image": "https://i.ibb.co/W4wHVqQj/photo-2025-09-19-13-01-25.jpg",
      "stats": null,
      "published": true
    },
    {
      "id": 39,
      "titleJa": "パートの女の子とフルタイムの女の子のサービスの違い",
      "titleZh": "兼職女孩和全職女孩服務區別",
      "titleEn": "Difference between part-time girl and full-time girl services",
      "excerpt": "当店の子たちは短期のアルバイトがほとんどであるため、長く働いているプロの子たちとは少し異なる場合がございます。",
      "excerptZh": "由於本店的女孩大多是短期兼職，她們可能與那些長期工作的專業女孩有些差異。",
      "excerptEn": "Since most of the girls at our establishment are short-term part-timers, they may differ somewhat from long-term professional girls.",
      "contentJa": "当店の女の子はほとんどが短期のアルバイトであるため、長期で働くプロの女の子とは少し異なる点があるかもしれません。\n\nもし、お客様が女の子との面会中やサービス中に、何かご期待に沿わない点があった場合、サービス内容に関する問題でも、お客様が不快に感じた点でも、必ずすぐに私にお伝えください！\n\n私は常にオンラインで対応しております",
      "contentZh": "由於本店的女孩大多是短期兼職，她們可能與那些長期工作的專業女孩有些差異。\n\n如果在您與女孩見面或服務過程中，發現有任何不符合您預期的情況，無論是服務過程中的問題還是您不舒服的地方，請一定要第一時間告訴我！\n\n我會隨時在線，並優先處理您的需求。\n我並不希望您默默忍受，也不希望您認為這是無所謂的事。\n任何不舒服的地方，無論是情緒還是服務問題，都可以隨時告訴我。\n\n每一次的放縱或容忍，可能會變成無數次的不愉快。\n對於來到本店的每一位客人，我從不僅僅視作顧客，我會把您視作遠道而來的朋友來對待。\n也正因如此，我希望您能在放鬆的過程中，沒有任何壓力，並且享受每一刻的愉悅。\n\n本店一直秉持著讓每一位來到這裡的客人都能開心地度過，並快樂地結束每一次的服務過程。\n\n我也深感謝那些一直支持我、信任我的朋友們，因為有你們的支持，這一切才有了更深的意義。❤️🥰",
      "contentEn": "As most of the girls at our establishment are short-term part-timers, they might differ somewhat from professional girls who work long-term.\n\nIf, during your meeting with a girl or the service, you find anything that doesn't meet your expectations, whether it's an issue with the service itself or something that makes you uncomfortable, please make sure to tell me immediately!\n\nI will be online at all times and will prioritize addressing your needs.\nI don't want you to silently endure it, nor do I want you to think it's insignificant.\nAny discomfort, whether emotional or a service issue, you can always tell me.\n\nEvery instance of letting things slide or tolerating something could turn into countless unpleasant experiences.\nFor every guest who comes to our establishment, I don't just see them as customers; I treat you as a friend who has traveled a long way.\nPrecisely because of this, I hope you can relax without any pressure and enjoy every moment of pleasure.\n\nOur establishment has always strived to ensure that every guest who comes here has a happy time and happily concludes each service.\n\nI am also deeply grateful to my friends who have always supported and trusted me, because with your support, all of this gains deeper meaning. ❤️🥰",
      "category": "日記",
      "date": "2026.3.18",
      "thumbnail": "https://i.ibb.co/93TNsb19/photo-2025-09-18-01-22-16.jpg",
      "stats": null,
      "published": true
    },
    {
      "id": 40,
      "titleJa": "番号7103",
      "titleZh": "番號7103",
      "titleEn": "No. 7103",
      "excerpt": "🇯🇵| 店長推薦 長時間割引（交通費込み）",
      "excerptZh": "🇯🇵| 店長推薦 長時間有折扣（包含交通費） ",
      "excerptEn": "🇯🇵| Manager's Recommendation: Long-term discount (including transportation fees)",
      "contentJa": "🇯🇵| 店長推薦 長時間割引（交通費込み）",
      "contentZh": "🇯🇵| 店長推薦\n長時間有折扣（包含交通費） ",
      "contentEn": "🇯🇵| Manager's Recommendation\nLong-term discount (transportation included)",
      "category": "出勤情報",
      "date": "2026.3.18",
      "thumbnail": "https://i.ibb.co/pvDZwfm0/photo-2025-09-18-12-11-46-2.jpg",
      "image": "https://i.ibb.co/jvdn1TQj/photo-2025-09-18-12-11-46.jpg",
      "stats": {
        "height": 158,
        "cup": "E",
        "age": 24,
        "weight": 46
      },
      "published": true
    },
    {
      "id": 41,
      "titleJa": "番号7104",
      "titleZh": "番號7104",
      "titleEn": "Part No. 7104",
      "excerpt": "🇯🇵| 店長推薦 長時間割引（交通費込み）",
      "excerptZh": "🇯🇵| 店長推薦 長時間有折扣（包含交通費） ",
      "excerptEn": "🇯🇵| Manager's Recommendation: Long-term discount (including transportation fees)",
      "contentJa": "🇯🇵| 店長推薦\n長時間割引（交通費込み）",
      "contentZh": "🇯🇵| 店長推薦\n長時間有折扣（包含交通費） ",
      "contentEn": "🇯🇵| Manager's Recommendation\nLong-term discounts (including transportation fees)",
      "category": "出勤情報",
      "date": "2026.3.18",
      "thumbnail": "https://i.ibb.co/SwKzFgws/photo-2025-09-18-12-14-52-2.jpg",
      "image": "https://i.ibb.co/fzT7n0fx/photo-2025-09-18-12-14-52.jpg",
      "stats": {
        "height": 162,
        "cup": "F",
        "age": 25,
        "weight": 55
      },
      "published": true
    },
    {
      "id": 42,
      "titleJa": "番号7105",
      "titleZh": "番號7105",
      "titleEn": "Number 7105",
      "excerpt": "🇯🇵| 店長推薦 長時間割引（交通費込み）",
      "excerptZh": "🇯🇵| 店長推薦 長時間有折扣（包含交通費） ",
      "excerptEn": "🇯🇵| Shop Manager's Recommendation: Long-term discount available (transportation included)",
      "contentJa": "🇯🇵| 店長推薦\n長期間割引（交通費込み）",
      "contentZh": "🇯🇵| 店長推薦\n長時間有折扣（包含交通費） ",
      "contentEn": "🇯🇵| Manager's Recommendation\nLong-term discount available (transportation included)",
      "category": "出勤情報",
      "date": "2026.3.18",
      "thumbnail": "https://i.ibb.co/8LXF5QtV/photo-2025-09-18-12-18-45-2.jpg",
      "image": "https://i.ibb.co/cc5ByvsX/photo-2025-09-18-12-18-45.jpg",
      "stats": {
        "height": 156,
        "cup": "F",
        "age": 48,
        "weight": 22
      },
      "published": true
    },
    {
      "id": 43,
      "titleJa": "番号7106",
      "titleZh": "番號7106",
      "titleEn": "Number 7106",
      "excerpt": "🇯🇵| 店長推薦 長時間割引（交通費込み）",
      "excerptZh": "🇯🇵| 店長推薦 長時間有折扣（包含交通費） ",
      "excerptEn": "🇯🇵| Manager's Recommendation: Long-term discount (including transportation fee)",
      "contentJa": "🇯🇵| 店長推薦 長時間割引（交通費込み）",
      "contentZh": "🇯🇵| 店長推薦 長時間有折扣（包含交通費） ",
      "contentEn": "🇯🇵| Manager's Recommendation: Long-term discounts available (including transportation costs)",
      "category": "出勤情報",
      "date": "2026.3.18",
      "thumbnail": "https://i.ibb.co/Zp63Ptr1/photo-2025-09-18-12-22-23.jpg",
      "image": "https://i.ibb.co/1G6dL7Vy/photo-2025-09-18-12-22-23-2.jpg",
      "stats": {
        "height": 163,
        "cup": "E",
        "age": 21,
        "weight": 45
      },
      "published": true
    },
    {
      "id": 44,
      "titleJa": "番号7107",
      "titleZh": "番號7107",
      "titleEn": "No. 7107",
      "excerpt": "店長推薦 長時間割引（交通費込み）",
      "excerptZh": "🇯🇵| 店長推薦 長時間有折扣（包含交通費） ",
      "excerptEn": "🇯🇵| Manager's Recommendation: Long-term discount (transportation included)",
      "contentJa": "🇯🇵| 店長のおすすめ\n長時間割引（交通費込み）",
      "contentZh": "🇯🇵| 店長推薦\n長時間有折扣（包含交通費） ",
      "contentEn": "🇯🇵| Manager's Pick\nLong-term discount (transportation included)",
      "category": "出勤情報",
      "date": "2026.3.18",
      "thumbnail": "https://i.ibb.co/qQcQ0bV/photo-2025-09-18-12-23-39-2.jpg",
      "image": "https://i.ibb.co/tw1Wykk0/photo-2025-09-18-12-23-39.jpg",
      "stats": {
        "height": 155,
        "cup": "D",
        "age": 19,
        "weight": 42
      },
      "published": true
    },
    {
      "id": 45,
      "titleJa": "番号7108",
      "titleZh": "番號7108",
      "titleEn": "No. 7108",
      "excerpt": "🇯🇵| 店長推薦 VIP限定 長時間割引あり（交通費込み）",
      "excerptZh": "🇯🇵| 店長推薦 只接待VIP 長時間有折扣（包含交通費） ",
      "excerptEn": "Manager's Recommendation: VIPs only. Long-term discount available (transportation fee included).",
      "contentJa": "店長のおすすめ VIP限定 長時間割引あり（交通費込み）",
      "contentZh": "🇯🇵| 店長推薦 只接待VIP\n長時間有折扣（包含交通費） ",
      "contentEn": "🇯🇵| Manager's Recommendation: VIPs Only\nLong-term discounts (transportation fees included)",
      "category": "出勤情報",
      "date": "2026.3.18",
      "thumbnail": "https://i.ibb.co/kgCFw8jv/photo-2025-09-18-12-24-57.jpg",
      "stats": {
        "height": 158,
        "cup": "D",
        "age": 20,
        "weight": 44
      },
      "published": true
    },
    {
      "id": 46,
      "titleJa": "番号7109",
      "titleZh": "番號7109",
      "titleEn": "Part No. 7109",
      "excerpt": "🇯🇵| 店長のおすすめ 長時間割引（交通費込み）",
      "excerptZh": "🇯🇵| 店長推薦 長時間有折扣（包含交通費） ",
      "excerptEn": "🇯🇵| Manager's Recommendation: Long-term discount (including transportation fee)",
      "contentJa": "🇯🇵| 店長推薦\n長時間割引あり（交通費込み）",
      "contentZh": "🇯🇵| 店長推薦\n長時間有折扣（包含交通費） ",
      "contentEn": "🇯🇵| Store Manager's Recommendation\nLong-term discount (including transportation fee)",
      "category": "出勤情報",
      "date": "2026.3.18",
      "thumbnail": "https://i.ibb.co/6chHz5pR/photo-2025-09-18-12-33-23.jpg",
      "stats": {
        "height": 157,
        "cup": "E",
        "age": 22,
        "weight": 47
      },
      "published": true
    },
    {
      "id": 47,
      "titleJa": "番号7110",
      "titleZh": "番號7110",
      "titleEn": "Item number 7110",
      "excerpt": "🇯🇵| 店長のおすすめ 長期割引（交通費込み）",
      "excerptZh": "🇯🇵| 店長推薦 長時間有折扣（包含交通費） ",
      "excerptEn": "Manager's Recommendation: Long-term discount (including transportation fees)",
      "contentJa": "🇯🇵| 店長推薦 長時間割引あり（交通費込み）",
      "contentZh": "🇯🇵| 店長推薦 長時間有折扣（包含交通費） ",
      "contentEn": "Manager's Recommendation: Long-term discounts available (including transportation fees)",
      "category": "出勤情報",
      "date": "2026.3.18",
      "thumbnail": "https://i.ibb.co/svK3WdW5/photo-2025-09-18-12-36-04.jpg",
      "image": "https://i.ibb.co/9HDRLTW0/photo-2025-09-18-12-36-05.jpg",
      "stats": {
        "height": 164,
        "cup": "E",
        "age": 25,
        "weight": 48
      },
      "published": true
    },
    {
      "id": 48,
      "titleJa": "番号7111",
      "titleZh": "番號7111",
      "titleEn": "Number 7111",
      "excerpt": "店長のおすすめ 長時間割引（交通費込み）",
      "excerptZh": "🇯🇵| 店長推薦 長時間有折扣（包含交通費） ",
      "excerptEn": "🇯🇵| Manager's Recommendation: Long-term discount available (transportation fee included).",
      "contentJa": "🇯🇵| 店長推薦！長時間割引（交通費込み）",
      "contentZh": "🇯🇵| 店長推薦 長時間有折扣（包含交通費） ",
      "contentEn": "🇯🇵| Manager's Recommendation: Long-term discount (including transportation fee)",
      "category": "出勤情報",
      "date": "2026.3.18",
      "thumbnail": "https://i.ibb.co/qMx3mf6T/photo-2025-09-18-12-37-33.jpg",
      "image": "https://i.ibb.co/5W4Hdgst/photo-2025-09-18-12-37-34.jpg",
      "stats": {
        "height": 150,
        "cup": "D",
        "age": 21,
        "weight": 46
      },
      "published": true
    },
    {
      "id": 49,
      "titleJa": "📢 ちょっとしたお知らせ",
      "titleZh": "📢 小提醒公告",
      "titleEn": "Friendly Reminder",
      "excerpt": "当店に短期アルバイトに来る女の子は、ほとんどが本業を持っています。",
      "excerptZh": "來本店短期兼職的女孩，大多數都有自己的正職工作。",
      "excerptEn": "Most girls working short-term part-time at our store also have full-time jobs.",
      "contentJa": "お客様各位\n\n短期アルバイトの女性スタッフのプライバシーと安全を守るため、サービス中に万が一、女性の顔を認識してしまったり、個人情報に触れることがあった場合でも、どうか心に留めておき、ご本人に直接尋ねたり、話題にしたりすることは固くお控えください。\n\n当店で短期アルバイトとして働く女性のほとんどは、",
      "contentZh": "親愛的各位兄弟：\n為了保護短期兼職女孩的隱私與安全，若在服務過程中不小心滑到女孩的臉，或發現女孩的相關資訊，請您默默享受即可，請勿主動詢問或提及。\n\n來本店短期兼職的女孩，大多數都有自己的正職工作。\n\n因此，我們特別希望大家能共同維護她們的隱私。\n也因為如此，您才能在這裡享受到來自各行各業、不同職業女孩所帶來的優質服務💕\n感謝您的理解與配合，讓我們一起創造安心、愉快的體驗！🥰",
      "contentEn": "Dear gentlemen,\nTo protect the privacy and safety of our short-term part-time girls, if you accidentally catch a glimpse of a girl's face during the service, or discover any information about her, please simply enjoy the experience silently, and do not actively ask or mention it.\n\nMost of the girls who work part-time here have their own full-time jobs.\n\nTherefore, we especially hope that everyone can jointly uphold their privacy.\nIt is precisely for this reason that you can enjoy the high-quality service provided by girls from all walks of life and diverse professions.\nThank you for your understanding and cooperation, and let us work together to create a safe and pleasant experience!",
      "category": "日記",
      "date": "2026.3.18",
      "thumbnail": "https://i.ibb.co/BKzmSXyX/photo-2026-03-18-16-56-45.jpg",
      "stats": null,
      "published": true
    },
    {
      "id": 38,
      "titleJa": "番號7102",
      "titleZh": "番號7102",
      "titleEn": "番號7102",
      "excerpt": "店長推薦 長時間割引（交通費込み）",
      "excerptZh": "🇯🇵| 店長推薦 長時間有折扣（包含交通費） ",
      "contentJa": "🇯🇵| 店長推薦\n長期間割引（交通費込み）",
      "contentZh": "🇯🇵| 店長推薦\n長時間有折扣（包含交通費） ",
      "contentEn": "🇯🇵| Manager's Recommendation\nLong-term discount (including transportation fee)",
      "category": "出勤情報",
      "date": "2026.3.17",
      "thumbnail": "https://i.ibb.co/7fmshT2/photo-2025-09-16-14-38-26-2.jpg",
      "image": "https://i.ibb.co/MyrH27sW/photo-2025-09-16-14-38-26.jpg",
      "stats": {
        "height": 164,
        "cup": "G",
        "age": 27,
        "weight": 50
      },
      "published": true,
      "excerptEn": "🇯🇵| Store Manager's Recommendation: Long-term discounts available (including transportation fees)"
    },
    {
      "id": 35,
      "titleJa": "番号7100",
      "titleZh": "番號7100",
      "titleEn": "Serial number 7100",
      "excerpt": "店長推薦 長時間割引（交通費込み）",
      "excerptZh": "🇯🇵| 店長推薦 長時間有折扣（包含交通費） ",
      "contentJa": "🇯🇵| 店長のおすすめ\n長時間割引あり（交通費込み）",
      "contentZh": "🇯🇵| 店長推薦\n長時間有折扣（包含交通費） ",
      "contentEn": "🇯🇵| Store Manager's Recommendation\nLong-term discount available (including transportation fees)",
      "category": "出勤情報",
      "date": "2026.3.17",
      "thumbnail": "https://i.ibb.co/sJmVLt8Y/photo-2025-09-16-14-35-54-2-0.jpg",
      "image": "https://i.ibb.co/MxbzCYnP/photo-2025-09-16-14-35-54.jpg",
      "stats": {
        "height": 165,
        "cup": "D",
        "age": 25,
        "weight": 46
      },
      "published": true,
      "excerptEn": "Store Manager's Recommendation: Long-term discounts available (including transportation fees).",
      "createdAt": "2026.3.17",
      "images": [
        "https://i.ibb.co/sJmVLt8Y/photo-2025-09-16-14-35-54-2-0.jpg",
        "https://i.ibb.co/Qvrd0cDD/photo-2025-09-16-14-35-54-0.jpg"
      ]
    },
    {
      "id": 36,
      "titleJa": "番号7101",
      "titleZh": "番號7101",
      "titleEn": "No. 7101",
      "excerpt": "🇯🇵| 店長推薦 長時間割引（交通費込み）",
      "excerptZh": "🇯🇵| 店長推薦 長時間有折扣（包含交通費） ",
      "contentJa": "🇯🇵| 店長推薦\n長時間割引（交通費込み）",
      "contentZh": "🇯🇵| 店長推薦\n長時間有折扣（包含交通費） ",
      "contentEn": "🇯🇵| Manager's Recommendation\nLong-term discount (transportation fees included)",
      "category": "出勤情報",
      "date": "2026.3.17",
      "thumbnail": "https://i.ibb.co/ynr0D5P7/photo-2025-09-16-14-37-16-2-0.jpg",
      "image": "https://i.ibb.co/mCFnpm9c/photo-2025-09-16-14-37-16.jpg",
      "stats": {
        "height": 169,
        "cup": "E",
        "age": 25,
        "weight": 48
      },
      "published": true,
      "excerptEn": "🇯🇵| Manager's Recommendation: Extended discount (transportation fees included)",
      "createdAt": "2026.3.17",
      "images": [
        "https://i.ibb.co/ynr0D5P7/photo-2025-09-16-14-37-16-2-0.jpg",
        "https://i.ibb.co/x8CS59yB/photo-2025-09-16-14-37-16-0.jpg"
      ]
    },
    {
      "id": 34,
      "titleJa": "東京の女性、好評｜デートの感想",
      "titleZh": "東京的小姐好評｜約完心得",
      "titleEn": "Tokyo Women: Good Reviews | Post-Meeting Experience",
      "excerpt": "皆様から繰り返しいただいた、揺るぎないご支持とご評価のフィードバックに、心より感謝申し上げます。",
      "excerptZh": "一次次的堅定和認可 謝謝你們給的回饋",
      "contentJa": "皆様から繰り返しいただいた、揺るぎないご支持とご評価のフィードバックに、心より感謝申し上げます。",
      "contentZh": "一次次的堅定和認可 謝謝你們給的回饋",
      "contentEn": "Your repeated affirmation and recognition. Thank you for your feedback.",
      "category": "客戶反饋",
      "date": "2026.03.16",
      "thumbnail": "https://i.ibb.co/YTNP8mJ6/message-Image-1773672161311.jpg",
      "stats": null,
      "published": true
    },
    {
      "id": 6,
      "titleJa": "3月限定プロモーション開催中！",
      "titleZh": "3月限定優惠活動！",
      "titleEn": "March Limited Promotion!",
      "contentJa": "3月限定プロモーション開催中！初回ご利用のお客様は特別割引あり。LINE・Telegramでお気軽にお問い合わせください。",
      "contentZh": "3月限定優惠活動！首次預約客人享特別折扣。歡迎透過 LINE、Telegram 詢問。",
      "contentEn": "March limited promotion! First-time customers get special discount. Contact via LINE or Telegram.",
      "excerpt": "3月限定プロモーション！初回割引実施中。",
      "excerptZh": "3月限定優惠！首次折扣進行中。",
      "date": "2026.03.15",
      "category": "お知らせ",
      "thumbnail": "https://i.ibb.co/LDz4kjy2/da3e46587b5effc2cb326e6c7af65a5e91787d0f33c2b3e547f286e653464814.png",
      "stats": null,
      "published": true
    },
    {
      "id": 10,
      "titleJa": "東京のお客様の声｜長年支えてくれたお友達",
      "titleZh": "東京的小姐好評｜默默支持的老朋友",
      "titleEn": "Tokyo Reviews - Long-term Support",
      "contentJa": "本当にオススメです！ずっと支えてくださり、毎回来るたびに友達に会うように嬉しい~\n\n#東京誠実 #信頼店 #真心対応 #一度のサービスで一生の友達\n\nTG指名ガール @tk6659\nLine ty5563",
      "contentZh": "真的超級推薦給你 一直以來都默默支持 每次來都會遇到好朋友一樣開心~\n\n#東京不套路 #誠信店家 #誠實相待 #一次服務終生朋友\n\nTG指名ガール連絡先 @tk6659\nLineの連絡先 ty5563",
      "contentEn": "Really super recommend! I've been silently supporting all along. Every time I come it feels like meeting old friends again~\n\n#TokyoNoTricks #HonestShop #Trustworthy #OneServiceLifetimeFriend\n\nTG @tk6659 | Line ty5563",
      "excerpt": "真的超級推薦給你 一直以來都默默支持 每次來都會遇到好朋友一樣開心~",
      "excerptJa": "本当にオススメ！ずっと支えてくれて、毎回来るたび友達に会うように嬉しい~",
      "excerptZh": "真的超級推薦給你 一直以來都默默支持 每次來都會遇到好朋友一樣開心~",
      "date": "2026.03.15",
      "category": "客戶反饋",
      "thumbnail": "./feedback/19cd7962129eb5235306a0f6bdd1d454.jpg",
      "stats": null,
      "published": true
    },
    {
      "id": 13,
      "titleJa": "東京のお客様の声｜最高の体験",
      "titleZh": "東京的小姐好評｜頂級體驗",
      "titleEn": "Tokyo Reviews - Top Experience",
      "contentJa": "最高です！3月に写真をアップします。\n\n本日、皆様からの次回のご注文を再びいただけて、心より嬉しく思います。\n皆様に、さらに素晴らしい「初めての体験」をしていただけることを楽しみにしております。\nご注文完了\n\n(皆様、ありがとうございます。日本以上の素晴らしい体験を必ずお約束いたします。)\n追伸：写真をお見せするのは、弊社の女性スタッフ",
      "contentZh": "頂級了！我3月會發圖片。\n\n真的超級開心今天能再次收到你們下次的訂單\n期待你們會感受到更棒的『初次體驗』\n訂單成功\n\n(謝謝你們，保證會讓你們有一個比日本更佳的體驗)\nPS: 讓照片出現是我們小姐姐想讓您想像一個更美好的體驗。",
      "contentEn": "Top-notch! I'll post pictures in March.\nWe are absolutely thrilled to receive your next order again today!\nWe hope you will experience an even better 'first-time experience'.\nOrder successful.\n(Thank you, we guarantee you'll have an even better experience than in Japan.)\nPS: Our staff member wanted the photos to appear to help you envision an even more wonderful experience.",
      "excerpt": "頂級了！真的超級開心今天能再次收到你們下次的訂單。期待更棒的初次體驗。",
      "excerptJa": "最高！また次のご予約いただけて本当に嬉しい。もっと素敵な初体験をお届けします。",
      "excerptZh": "頂級了！真的超級開心今天能再次收到你們下次的訂單。期待更棒的初次體驗。",
      "date": "2026.03.15",
      "category": "客戶反饋",
      "thumbnail": "./feedback/e35aa753e659c440a6e76d8320a786bb.jpg",
      "stats": null,
      "published": true
    },
    {
      "id": 1,
      "titleJa": "人気No.1　出勤中🌸",
      "titleZh": "人氣No.1　出勤中🌸",
      "titleEn": "Top Pick On Duty 🌸",
      "contentJa": "本日出勤中です🌸\n身長163cm、Cカップ、26歳。清楚系美女。初回のお客様は特別割引あり！ぜひLINEでお問合わせください。",
      "contentZh": "本日出勤中🌸\n身高163cm、C罩杯、26歲。清楚系美女。初次預約有特別優惠！歡迎通過LINE詢問。",
      "contentEn": "On duty today 🌸\n163cm, C-cup, 26yo. Innocent beauty. First-time discount! Contact via LINE.",
      "excerpt": "人気No.1 出勤中🌸 163cm、C罩杯、26歲。",
      "excerptJa": "人気No.1 出勤中🌸 163cm、Cカップ、26歳。",
      "excerptZh": "人氣No.1 出勤中🌸 163cm、C罩杯、26歲。",
      "date": "2026.03.14",
      "category": "出勤情報",
      "thumbnail": "./attendance/SaveClip.App_454488312_462785996572428_6882859839536539659_n-2.jpg",
      "stats": {
        "height": 163,
        "cup": "C",
        "age": 26,
        "weight": 45
      },
      "published": true
    },
    {
      "id": 2,
      "titleJa": "NEW　出勤中💐",
      "titleZh": "新人　出勤中💐",
      "titleEn": "NEW On Duty 💐",
      "contentJa": "本日出勤中です💐\n身長160cm、Eカップ、23歳。素人感あふれる笑顔がとても可愛い！ぜひお問合わせください。",
      "contentZh": "本日出勤中💐\n身高160cm、E罩杯、23歲。充滿素人感的笑容非常可愛！歡迎詢問。",
      "contentEn": "On duty today 💐\n160cm, E-cup, 23yo. Her amateur smile is very cute! Inquire via LINE.",
      "excerpt": "NEW 出勤中💐 160cm、E罩杯、23歲。",
      "excerptJa": "NEW 出勤中💐 160cm、Eカップ、23歳。",
      "excerptZh": "新人 出勤中💐 160cm、E罩杯、23歲。",
      "date": "2026.03.14",
      "category": "出勤情報",
      "thumbnail": "./attendance/photo_2025-05-14_17-19-42.jpg",
      "stats": {
        "height": 160,
        "cup": "E",
        "age": 23,
        "weight": 46
      },
      "published": true
    },
    {
      "id": 5,
      "titleJa": "リピ率高　出勤中💕",
      "titleZh": "回頭客高　出勤中💕",
      "titleEn": "High Repeat On Duty 💕",
      "contentJa": "今週も出勤中です💕\n162cm、Dカップ、25歳。リピーターも多く、特に混浴サービスが人気！今週末も予約受付中です。",
      "contentZh": "這週也出勤中💕\n162cm、D罩杯、25歲。回頭客很多，特別是混浴服務很受歡迎！本週末也接受預約。",
      "contentEn": "On duty this week 💕\n162cm, D-cup, 25yo. Many repeat customers, bath service especially popular! Accepting bookings this weekend.",
      "excerpt": "今週も出勤！混浴人気、今週末も予約受付中。",
      "excerptZh": "這週也出勤！混浴服務很受歡迎，本週末接受預約。",
      "date": "2026.03.14",
      "category": "出勤情報",
      "thumbnail": "./attendance/SaveClip.App_482210811_617057904556271_3428309151914796135_n-1-2.jpg",
      "stats": {
        "height": 162,
        "cup": "D",
        "age": 25,
        "weight": 47
      },
      "published": true
    },
    {
      "id": 28,
      "titleJa": "おすすめ　出勤中✨",
      "titleZh": "推薦　出勤中✨",
      "titleEn": "Recommended On Duty ✨",
      "contentJa": "本日出勤中です✨\n身長164cm、Gカップ、24歳。美脚系。ぜひお問合わせください。",
      "contentZh": "本日出勤中✨\n身高164cm、G罩杯、24歲。美腿系。歡迎詢問。",
      "contentEn": "On duty today ✨\n164cm, G-cup, 24yo. Slim legs type. Inquire via LINE.",
      "excerpt": "おすすめ 出勤中✨ 164cm、G罩杯、24歲。",
      "excerptJa": "おすすめ 出勤中✨ 164cm、Gカップ、24歳。",
      "excerptZh": "推薦 出勤中✨ 164cm、G罩杯、24歲。",
      "date": "2026.03.14",
      "category": "出勤情報",
      "thumbnail": "./attendance/SaveClip.App_487873851_638067385788656_1757071670341084752_n-2.jpg",
      "stats": {
        "height": 164,
        "cup": "G",
        "age": 24,
        "weight": 48
      },
      "published": true
    },
    {
      "id": 29,
      "titleJa": "出勤中🌸",
      "titleZh": "出勤中🌸",
      "titleEn": "On Duty 🌸",
      "contentJa": "本日出勤中です🌸\n身長161cm、Eカップ、25歳。素人系。ぜひお問合わせください。",
      "contentZh": "本日出勤中🌸\n身高161cm、E罩杯、25歲。素人系。歡迎詢問。",
      "contentEn": "On duty today 🌸\n161cm, E-cup, 25yo. Amateur type. Inquire via LINE.",
      "excerpt": "出勤中🌸 161cm、E罩杯、25歲。",
      "excerptJa": "出勤中🌸 161cm、Eカップ、25歳。",
      "excerptZh": "出勤中🌸 161cm、E罩杯、25歲。",
      "date": "2026.03.14",
      "category": "出勤情報",
      "thumbnail": "./attendance/SaveClip.App_470198996_558775093717886_6211310752276090855_n-2.jpg",
      "stats": {
        "height": 161,
        "cup": "E",
        "age": 25,
        "weight": 49
      },
      "published": true
    },
    {
      "id": 30,
      "titleJa": "HOT　出勤中🔥",
      "titleZh": "HOT　出勤中🔥",
      "titleEn": "HOT On Duty 🔥",
      "contentJa": "本日出勤中です🔥\n身長164cm、Dカップ、28歳。セクシー系。ぜひお問合わせください。",
      "contentZh": "本日出勤中🔥\n身高164cm、D罩杯、28歲。性感系。歡迎詢問。",
      "contentEn": "On duty today 🔥\n164cm, D-cup, 28yo. Sexy type. Inquire via LINE.",
      "excerpt": "HOT 出勤中🔥 164cm、D罩杯、28歲。",
      "excerptJa": "HOT 出勤中🔥 164cm、Dカップ、28歳。",
      "excerptZh": "HOT 出勤中🔥 164cm、D罩杯、28歲。",
      "date": "2026.03.14",
      "category": "出勤情報",
      "thumbnail": "./attendance/SaveClip.App_491898753_18029838368648108_3514056197024902867_n-1.jpg",
      "stats": {
        "height": 164,
        "cup": "D",
        "age": 28,
        "weight": 45
      },
      "published": true
    },
    {
      "id": 31,
      "titleJa": "出勤中💕",
      "titleZh": "出勤中💕",
      "titleEn": "On Duty 💕",
      "contentJa": "本日出勤中です💕\n身長162cm、Dカップ、25歳。ぜひお問合わせください。",
      "contentZh": "本日出勤中💕\n身高162cm、D罩杯、25歲。歡迎詢問。",
      "contentEn": "On duty today 💕\n162cm, D-cup, 25yo. Inquire via LINE.",
      "excerpt": "出勤中💕 162cm、D罩杯、25歲。",
      "excerptJa": "出勤中💕 162cm、Dカップ、25歳。",
      "excerptZh": "出勤中💕 162cm、D罩杯、25歲。",
      "date": "2026.03.14",
      "category": "出勤情報",
      "thumbnail": "./attendance/photo_2025-05-02_23-47-07.jpg",
      "stats": {
        "height": 162,
        "cup": "D",
        "age": 25,
        "weight": 47
      },
      "published": true
    },
    {
      "id": 32,
      "titleJa": "NEW　出勤中🌟",
      "titleZh": "新人　出勤中🌟",
      "titleEn": "NEW On Duty 🌟",
      "contentJa": "本日出勤中です🌟\n身長161cm、Eカップ、24歳。ぜひお問合わせください。",
      "contentZh": "本日出勤中🌟\n身高161cm、E罩杯、24歲。歡迎詢問。",
      "contentEn": "On duty today 🌟\n161cm, E-cup, 24yo. Inquire via LINE.",
      "excerpt": "NEW 出勤中🌟 161cm、E罩杯、24歲。",
      "excerptJa": "NEW 出勤中🌟 161cm、Eカップ、24歳。",
      "excerptZh": "新人 出勤中🌟 161cm、E罩杯、24歲。",
      "date": "2026.03.14",
      "category": "出勤情報",
      "thumbnail": "./attendance/photo_2025-05-02_23-47-42.jpg",
      "stats": {
        "height": 161,
        "cup": "E",
        "age": 24,
        "weight": 46
      },
      "published": true
    },
    {
      "id": 11,
      "titleJa": "東京のお客様の声｜大満足・とても積極的",
      "titleZh": "東京的小姐好評｜很滿意、非常主動",
      "titleEn": "Tokyo Reviews - Very Satisfied & Proactive",
      "contentJa": "大満足😍 とても積極的で最高でした\n\nスタイルは？顔は可愛い？\n年齢は？26歳くらいかな\n\n友達が来たら絶対試してもらう！\nまた来てね～初回ありがとう\n\n連絡先 @tk6659、ty5563",
      "contentZh": "很滿意😍 非常主動 很好整體\n\n女生身材怎麼樣？臉蛋漂亮嗎？\n你覺得她保養歲數？26左右吧\n\n下次有朋友來 一定叫他試試嘿嘿\n期待哥哥下次在來捧場\n第一次配合感謝哥哥的信任與支持\n\n連絡先 @tk6659、ty5563",
      "contentEn": "Very satisfied 😍 Very proactive, great overall\n\nHow's her figure? Pretty face? She looks about 26.\n\nNext time a friend comes I'll definitely have them try!\nLooking forward to your next visit~ Thanks for your trust and support on first time.\n\nContact @tk6659, ty5563",
      "excerpt": "很滿意😍 非常主動 很好整體。下次有朋友來 一定叫他試試嘿嘿",
      "excerptJa": "大満足😍 とても積極的で最高。友達が来たら絶対試してもらう！",
      "excerptZh": "很滿意😍 非常主動 很好整體。下次有朋友來 一定叫他試試嘿嘿",
      "date": "2026.03.14",
      "category": "客戶反饋",
      "thumbnail": "./feedback/cbcf9bb4b4f7f2f611b23f33ba10eb16.jpg",
      "stats": null,
      "published": true
    },
    {
      "id": 12,
      "titleJa": "東京のお客様の声｜体験後レビュー",
      "titleZh": "東京的小姐好評｜約完心得",
      "titleEn": "Tokyo Reviews - After Session",
      "contentJa": "積極的？いいね！\nサービスが積極的で女の子も最高\n\n体験後レビュー\n新規のお客様ありがとう~❤️\n\nTG @tk6659\nLine ty5563",
      "contentZh": "會主動嘛？不錯啊\n服務很主動 女生很棒\n\n約完心得\n感謝新朋友的支持~❤️\n\nTG指名ガール連絡先 @tk6659\nLineの連絡先 ty5563",
      "contentEn": "Is she proactive? Yeah, not bad!\nService is very proactive, girl is great.\n\nAfter session心得\nThanks for the support from new friends~❤️\n\nTG @tk6659 | Line ty5563",
      "excerpt": "服務很主動 女生很棒。約完心得 感謝新朋友的支持~❤️",
      "excerptJa": "サービスが積極的で女の子も最高。新規のお客様ありがとう~❤️",
      "excerptZh": "服務很主動 女生很棒。約完心得 感謝新朋友的支持~❤️",
      "date": "2026.03.13",
      "category": "客戶反饋",
      "thumbnail": "./feedback/d0f2bb9ae07e2aba7d9eef7a10aa91fb.jpg",
      "stats": null,
      "published": true
    },
    {
      "id": 14,
      "titleJa": "東京のお客様の声｜プリンセスの感想",
      "titleZh": "東京的小姐好評｜公主感嘆",
      "titleEn": "Tokyo Reviews - Princess Feedback",
      "contentJa": "悠悠夜桜 東京出張【外国人対応】\n\nプリンセス：今は悠悠を信じる...\nサービス：本人は可愛いお姉さん\nスタイル：モデル級以上\nタイプ：スポーティ\n彼女：なかなか帰らなかった\nOK〜",
      "contentZh": "軸白 悠悠夜桜東京外送【不限外銷客】\n\n公主感嘆：現在會相信悠悠...\n女方服務：真實本人是可愛的小姐姐\n女方身材：不只是模特兒\n女方類型：運動投入\n小姐姐：一直不肯離開\n可以喔",
      "contentEn": "Yuyu Yozakura Tokyo Delivery [All Clients Welcome]\n\nPrincess says: Now I believe in Yuyu...\nHer service: Real person is a cute girl\nHer figure: More than model-level\nHer type: Sporty\nShe: Didn't want to leave\nCan do~",
      "excerpt": "公主感嘆：現在會相信悠悠。女方服務真實本人可愛，身材不只是模特兒。",
      "excerptJa": "プリンセス：今は悠悠を信じる。本人可愛い、スタイルはモデル級以上。",
      "excerptZh": "公主感嘆：現在會相信悠悠。女方服務真實本人可愛，身材不只是模特兒。",
      "date": "2026.03.12",
      "category": "客戶反饋",
      "thumbnail": "./feedback/ec77dcc97959a83e7277e554c476c29a.jpg",
      "stats": null,
      "published": true
    },
    {
      "id": 15,
      "titleJa": "東京のお客様の声｜悠悠夜桜",
      "titleZh": "東京的小姐好評｜悠悠夜桜",
      "titleEn": "Tokyo Reviews - Yuyu Yozakura",
      "contentJa": "世界は広い、私たちを見つけてくれて本当に嬉しい！\nこの出会いは始まりに過ぎません -\n\nTG @tk6659\nLine ty5563\n\n新宿店 東京九山町1-12",
      "contentZh": "世界那麼大，你能找到我們，我們真的超級開心！\n分外難得相遇只是開始 -\n\nTG指名ガール連絡先 @tk6659\nlineの連絡先 ty5563\n\n新宿店 東京區九山町1-12",
      "contentEn": "The world is so big, and you found us - we're really happy!\nThis rare encounter is just the beginning -\n\nTG @tk6659 | Line ty5563\n\nShinjuku Store Tokyo",
      "excerpt": "世界那麼大，你能找到我們，我們真的超級開心！分外難得相遇只是開始。",
      "excerptJa": "世界は広い、私たちを見つけてくれて本当に嬉しい！この出会いは始まりに過ぎません。",
      "excerptZh": "世界那麼大，你能找到我們，我們真的超級開心！分外難得相遇只是開始。",
      "date": "2026.03.11",
      "category": "客戶反饋",
      "thumbnail": "./feedback/f9df7e37c19a51dd725e20c6e400e333.jpg",
      "stats": null,
      "published": true
    },
    {
      "id": 3,
      "titleJa": "3月のおすすめ女の子まとめ✨",
      "titleZh": "3月推薦女孩總整理✨",
      "titleEn": "March Recommendations ✨",
      "contentJa": "3月のおすすめをまとめました！\n\n🌸 アイちゃん（161cm/E/24歳） - 清楚系No.1\n🌸 リナちゃん（164cm/G/24歳） - 美脚女王\n🌸 サキちゃん（164cm/D/28歳） - セクシー系\n\n今月は初回割引も実施中！LINE・Telegramでお気軽にお問い合わせください。",
      "contentZh": "3月推薦女孩整理！\n\n🌸 小愛（161cm/E/24歲） - 清楚系No.1\n🌸 小莉娜（164cm/G/24歲） - 美腿女王\n🌸 小沙希（164cm/D/28歲） - 性感系\n\n本月有初次折扣！歡迎透過LINE、Telegram詢問。",
      "contentEn": "March recommendations!\n\n🌸 Ai (161cm/E/24yo) - Innocent type No.1\n🌸 Rina (164cm/G/24yo) - Slim legs queen\n🌸 Saki (164cm/D/28yo) - Sexy type\n\nFirst-time discount this month! Contact via LINE or Telegram.",
      "excerpt": "3月のおすすめ女の子をまとめました！人気No.1のアイちゃんやサキちゃんなど。",
      "excerptZh": "3月推薦女孩整理！包含人氣No.1小愛和小沙希等。",
      "date": "2026.03.01",
      "category": "お知らせ",
      "thumbnail": "https://www.yu5560.com/wp-content/uploads/2025/05/photo_2025-05-02_19-24-15.jpg",
      "stats": null,
      "published": true
    },
    {
      "id": 7,
      "titleJa": "新エリア対応：荒川区・足立区",
      "titleZh": "新服務地區：荒川區、足立區",
      "titleEn": "New Areas: Arakawa & Adachi",
      "contentJa": "荒川区・足立区も出張可能になりました。ご利用エリアの詳細はLINEでお問い合わせください。",
      "contentZh": "荒川區、足立區正式開放出張。詳細請洽 LINE。",
      "contentEn": "Arakawa and Adachi now available. Contact LINE for details.",
      "excerpt": "荒川区・足立区も出張可能に。",
      "excerptZh": "荒川區、足立區開放出張。",
      "date": "2026.02.20",
      "category": "お知らせ",
      "thumbnail": null,
      "stats": null,
      "published": true
    },
    {
      "id": 8,
      "titleJa": "お正月特別コース",
      "titleZh": "新年特別方案",
      "titleEn": "New Year Special",
      "contentJa": "お正月特別コース期間限定追加。詳細はLINEでお問合わせください。",
      "contentZh": "新年特別方案限期加入，詳情請洽 LINE。",
      "contentEn": "New Year special course available. Contact LINE for details.",
      "excerpt": "お正月特別コース追加。",
      "excerptZh": "新年特別方案加入。",
      "date": "2026.01.05",
      "category": "お知らせ",
      "thumbnail": null,
      "stats": null,
      "published": true
    },
    {
      "id": 9,
      "titleJa": "女の子ラインナップ大幅リニューアル",
      "titleZh": "女孩陣容大幅更新",
      "titleEn": "Lineup Major Update",
      "contentJa": "女の子ラインナップを大幅リニューアル。新人入店続々！ぜひLINEで最新情報をご確認ください。",
      "contentZh": "女孩陣容大幅更新，新人持續加入！歡迎透過 LINE 查看最新資訊。",
      "contentEn": "Major lineup update. New girls joining! Check LINE for latest info.",
      "excerpt": "ラインナップ大幅リニューアル、新人続々。",
      "excerptZh": "陣容大幅更新，新人持續加入。",
      "date": "2025.12.20",
      "category": "お知らせ",
      "thumbnail": null,
      "stats": null,
      "published": true
    },
    {
      "id": 4,
      "titleJa": "身長156cm 22歳 Dカップ 47kg #純粋な誘惑 天使の顔に悪魔のくびれ",
      "titleZh": "身高156cm 年齡22歲 D罩杯 體重47kg #純誘惑 天使臉龐魔鬼腰",
      "titleEn": "Height: 156cm Age: 22 Cup size: D cup Weight: 47kg #Pure Temptation Angel face and devil's waist",
      "contentJa": "身長156cm、22歳、Dカップ、47kg。天使のような顔に悪魔のようなくびれ。#純粋な誘惑",
      "contentZh": "身高156cm 年齡22歲 D罩杯 體重47kg #純誘惑 天使臉龐魔鬼腰",
      "contentEn": "Height: 156cm Age: 22 Cup size: D cup Weight: 47kg #Pure Temptation Angel face and devil's waist",
      "excerpt": "Height: 156cm Age: 22 Cup size: D cup Weight: 47kg #Pure Temptation",
      "excerptJa": "身長156cm 22歳 Dカップ 47kg #純粋な誘惑",
      "excerptZh": "身高156cm 年齡22歲 D罩杯 體重47kg #純誘惑",
      "date": "2025.05.01",
      "category": "日記",
      "thumbnail": "./diary/f30e84a519b77894b1da79b3f10f86f9c26a09d1.31.9.9.3.jpeg",
      "stats": null,
      "published": true
    },
    {
      "id": 16,
      "titleJa": "夜桜の夢 東京出張サービス 🎎",
      "titleZh": "夜桜の夢東京外送服務 🎎",
      "titleEn": "Night Cherry Blossom Dream Tokyo Outing Service 🎎",
      "contentJa": "身長161cm、24歳、Fカップ、48kg。情熱的で経験豊富、初心者にもおすすめ。雰囲気作りが得意です。",
      "contentZh": "身高161cm 年齡24歲 F罩杯 體重48kg 熱情投入、經驗豐富、適合新手，態度好能營造良好氛圍。",
      "contentEn": "Height: 161cm Age: 24 Cup size: F cup Weight: 48kg Passionate in bed, sexually experienced, suitable for beginners, has a good attitude and can create a good atmosphere.",
      "excerpt": "Night Cherry Blossom Dream Tokyo Outing Service 🎎",
      "excerptJa": "夜桜の夢 東京出張サービス 🎎",
      "excerptZh": "夜桜の夢東京外送服務 🎎",
      "date": "2025.05.01",
      "category": "日記",
      "thumbnail": "./diary/4533254b85f217190f09f7a5dc93e1bce6470b56.31.9.9.3.jpeg",
      "stats": null,
      "published": true
    },
    {
      "id": 17,
      "titleJa": "#日本 #東京 #吉原ソープ #日本風呂",
      "titleZh": "#日本東京 #吉原泡泡浴 #日本泡泡浴",
      "titleEn": "#Japan, Tokyo, Japan #Japan, Tokyo, foreign country #Japan, Tokyo, student sister #Yoshiwara Bubble Bubble Bath #Japanese Bubble Bubble Bath",
      "contentJa": "身長159cm、24歳、Dカップ、46kg。最も美しく優雅な白肌の美人、セクシーで可愛い。",
      "contentZh": "身高159cm 年齡24歲 D罩杯 體重46kg。最美麗優雅的白皙美人，性感可愛。",
      "contentEn": "Height: 159 years old: 24 years old Cup size: D cup weight: 46 years old. She is the most beautiful, elegant white-skinned beauty, sensual and cute.",
      "excerpt": "#Japan Tokyo #Yoshiwara Bubble Bubble Bath",
      "excerptJa": "#日本東京 #吉原ソープ",
      "excerptZh": "#日本東京 #吉原泡泡浴",
      "date": "2025.05.01",
      "category": "日記",
      "thumbnail": "./diary/3d912eef6dd3c16bb14eea1b17cbe2640e43aea8.31.9.9.3.jpeg",
      "stats": null,
      "published": true
    },
    {
      "id": 18,
      "titleJa": "夜桜の夢 東京出張サービス 🎎",
      "titleZh": "夜桜の夢東京外送服務 🎎",
      "titleEn": "Night Cherry Blossom Dream Tokyo Outing Service 🎎",
      "contentJa": "身長163cm、26歳、Cカップ、45kg。#白肌美人 #美脚 細くて曲線美のある体型が魅力。",
      "contentZh": "身高163cm 年齡26歲 C罩杯 體重45kg #白皙美麗 #美腿 喜愛她纖細有曲線的身材。",
      "contentEn": "Height: 163cm Age: 26 Cup size: C Weight: 45kg #Fair-skinned and beautiful #Beautiful legs I love her slender, curvaceous figure.",
      "excerpt": "Night Cherry Blossom Dream Tokyo Outing Service 🎎",
      "excerptJa": "夜桜の夢 東京出張サービス 🎎",
      "excerptZh": "夜桜の夢東京外送服務 🎎",
      "date": "2025.05.01",
      "category": "日記",
      "thumbnail": "./diary/a2e08a2f9cc2a2e201226ad849bf89b945926988.31.9.9.3.jpeg",
      "stats": null,
      "published": true
    },
    {
      "id": 19,
      "titleJa": "悠悠夜桜 東京出張【外国人対応】",
      "titleZh": "悠悠夜桜東京外送【不限外國客】",
      "titleEn": "Yuyuya Sakura Tokyo Overseas Transportation [Unlimited Foreign Registered Customers]",
      "contentJa": "身長158cm、28歳、Eカップ、46kg。❤️ TG指名 @tk6659 ❤️ LINE ty5563",
      "contentZh": "身高158cm 年齡28歲 E罩杯 體重46kg ❤️ TG指名 @tk6659 ❤️ LINE ty5563",
      "contentEn": "Height: 158cm Age: 28 Cup Size: E Cup Weight: 46kg ❤️ \"TG Designated Girl Contact\" @tk6659 ❤️ \"LINE Contact\" ty5563",
      "excerpt": "Yuyuya Sakura Tokyo Overseas Transportation [Unlimited Foreign Registered Customers]",
      "excerptJa": "悠悠夜桜 東京出張【外国人対応】",
      "excerptZh": "悠悠夜桜東京外送【不限外國客】",
      "date": "2025.04.20",
      "category": "日記",
      "thumbnail": "./diary/133e04fc1bfc56344cb56b5e86bd293af79e1573.31.9.9.3.jpeg",
      "stats": null,
      "published": true
    },
    {
      "id": 20,
      "titleJa": "悠悠夜桜 東京出張 TGtk6659",
      "titleZh": "悠悠夜桜東京外送 TGtk6659",
      "titleEn": "Yuyu Yozakura Tokyo Outbound TGtk6659",
      "contentJa": "身長162cm、24歳、Dカップ、45kg。公定価格36,000円。❤️ TG @tk6659 ❤️ LINE ty5563",
      "contentZh": "身高162cm 年齡24歲 D罩杯 體重45kg 公定價36,000円 ❤️ TG @tk6659 ❤️ LINE ty5563",
      "contentEn": "Height: 162 years old: 24 years old Cup size: D cup weight: 45 public price: 36,000 yen ❤️ \"TG designated female connection method\" @tk6659❤️ \"Line Contact\" ty5563",
      "excerpt": "Yuyu Yozakura Tokyo Outbound TGtk6659",
      "excerptJa": "悠悠夜桜 東京出張 TGtk6659",
      "excerptZh": "悠悠夜桜東京外送 TGtk6659",
      "date": "2025.04.20",
      "category": "日記",
      "thumbnail": "./diary/df0a295624619df612686555bf0918d079243940.31.9.9.3.jpeg",
      "stats": null,
      "published": true
    },
    {
      "id": 21,
      "titleJa": "#日本発 海外旅行 桜姉さん厳選 欲望の都",
      "titleZh": "#日本出發海外旅行 櫻花姐姐精選 慾望之都",
      "titleEn": "#Japan departure overseas trip Sakura flower sister chief selection city of desire face cash exchange 100 minutes 100 person photo piece",
      "contentJa": "情報：162cm 46kg C 22歳 #地域：東京🇯🇵 純粋な瞳、白肌、青春セクシー系。東京を訪れる外国人お客様も大歓迎 ✨",
      "contentZh": "資訊：162cm 46kg C 22歲 #地區：東京🇯🇵 純淨眼眸、白皙肌膚、青春性感型。外國客來東京也非常歡迎 ✨",
      "contentEn": "Information: 162cm 46kg C 22 years old # Region: Tokyo 🇯🇵 Pure eyes, fair skin, youthful and sexy type. Foreign customers visiting Tokyo are also very welcome ✨",
      "excerpt": "#Japan departure overseas trip Sakura flower sister",
      "excerptJa": "#日本発 海外旅行 桜姉さん厳選",
      "excerptZh": "#日本出發海外旅行 櫻花姐姐精選",
      "date": "2024.10.25",
      "category": "日記",
      "thumbnail": "./diary/0f2717c37c6ac624b35a6245dd27823b2d67b290.31.9.9.3.jpeg",
      "stats": null,
      "published": true
    },
    {
      "id": 22,
      "titleJa": "東京出張料金 ty5563",
      "titleZh": "東京外送費用 ty5563",
      "titleEn": "Tokyo overseas delivery fee ty5563",
      "contentJa": "情報：160cm 45kg C 21歳 #地域：東京🇯🇵 純粋な女子大生、若く完璧な体型がたまらない！TG @tk6659 💬 LINE ty5563",
      "contentZh": "資訊：160cm 45kg C 21歲 #地區：東京🇯🇵 純淨學生妹，青春完美身材令人無法抗拒！TG @tk6659 💬 LINE ty5563",
      "contentEn": "Information: 160cm 45kg C 21 years old # Region: Tokyo 🇯🇵 A pure schoolgirl, her youthful and perfect figure is irresistible! \"TG girl contact information\" @tk6659 💬 \"LINE contact information\" ty5563",
      "excerpt": "Tokyo overseas delivery fee ty5563",
      "excerptJa": "東京出張料金 ty5563",
      "excerptZh": "東京外送費用 ty5563",
      "date": "2024.10.25",
      "category": "日記",
      "thumbnail": "./diary/ae00402020dd1413009abcbf64f823cb5a2fc2d0.31.9.9.3.jpeg",
      "stats": null,
      "published": true
    },
    {
      "id": 23,
      "titleJa": "#今日限定 #巨乳お姉さん",
      "titleZh": "#今日限定 #巨乳姐姐",
      "titleEn": "#Limited today #Limited today #Limited today #Big breasted sister",
      "contentJa": "情報：162cm 46kg D 25歳 #地域：東京🇯🇵 本日限定 巨乳ガール TG @tk6659 💬 LINE ty5563",
      "contentZh": "資訊：162cm 46kg D 25歲 #地區：東京🇯🇵 今日限定 巨乳女孩 TG @tk6659 💬 LINE ty5563",
      "contentEn": "Information: 162cm 46kg D 25 years old # Region: Tokyo 🇯🇵 Today only Busty girl \"TG designated girl contact\" @tk6659 💬 \"Line contact\" ty5563",
      "excerpt": "#Limited today #Big breasted sister",
      "excerptJa": "#今日限定 #巨乳お姉さん",
      "excerptZh": "#今日限定 #巨乳姐姐",
      "date": "2024.10.25",
      "category": "日記",
      "thumbnail": "./diary/08519962adc99a4b481634431dfe523a00cf5fd2.31.9.9.3.jpeg",
      "stats": null,
      "published": true
    },
    {
      "id": 24,
      "titleJa": "#日本発 #旅行必需品",
      "titleZh": "#日本出發 #旅行必備",
      "titleEn": "#Departure from Japan #Travel essentials",
      "contentJa": "情報：160cm 45kg C+ 22歳 #地域：東京🇯🇵 超美人、雰囲気抜群、スタイル最高 TG @tk6659 💬 LINE ty5563",
      "contentZh": "資訊：160cm 45kg C+ 22歲 #地區：東京🇯🇵 超級美麗、氣質佳、身材好 TG @tk6659 💬 LINE ty5563",
      "contentEn": "Information: 160cm 45kg C+ 22 years old # Region: Tokyo 🇯🇵 Super beautiful, super good temperament, super figure \"TG designated girl contact\" @tk6659 💬 \"Line contact\" ty5563",
      "excerpt": "#Departure from Japan #Travel essentials",
      "excerptJa": "#日本発 #旅行必需品",
      "excerptZh": "#日本出發 #旅行必備",
      "date": "2024.10.25",
      "category": "日記",
      "thumbnail": "./diary/139504602c39eebf6fba00cf5d3fcf0a7af7ce1f.31.9.9.3.jpeg",
      "stats": null,
      "published": true
    },
    {
      "id": 25,
      "titleJa": "#お問合せ：163/46/C/22歳 #地域：東京🇯🇵",
      "titleZh": "#詢問：163/46/C/22歲 #地區：東京🇯🇵",
      "titleEn": "#Inquiry: 163/46/C/22 years old #Area: Tokyo🇯🇵",
      "contentJa": "経験少なめの良い子、純粋で可愛い、白肌で柔らか、頬をつねりたくなる小顔 ✨ TG @tk6659 💬 LINE ty5563",
      "contentZh": "經驗少的好女孩，純淨可愛、白皙柔軟、小臉讓人想捏 ✨ TG @tk6659 💬 LINE ty5563",
      "contentEn": "A good girl with little experience, pure and cute, fair-skinned and soft, small face that you really want to pinch ✨ \"TG designated girl contact information\" @tk6659 💬 \"Line contact information\" ty5563",
      "excerpt": "#Inquiry: 163/46/C/22 years old #Area: Tokyo🇯🇵",
      "excerptJa": "#お問合せ：163/46/C/22歳 #地域：東京🇯🇵",
      "excerptZh": "#詢問：163/46/C/22歲 #地區：東京🇯🇵",
      "date": "2024.10.25",
      "category": "日記",
      "thumbnail": "./diary/82cec84af98ece563489eda38731eb1c2cc5ea81.31.9.9.3.jpeg",
      "stats": null,
      "published": true
    },
    {
      "id": 26,
      "titleJa": "東京でデート探してる？松島悠悠",
      "titleZh": "在東京找約會？松島悠悠",
      "titleEn": "Looking for a date in Tokyo? Matsushima Yuyu",
      "contentJa": "参考：161cm 46kg D+ 27歳 #地域：東京🇯🇵 TG @tk6659 💬 LINE ty5563",
      "contentZh": "參考：161cm 46kg D+ 27歲 #地區：東京🇯🇵 TG @tk6659 💬 LINE ty5563",
      "contentEn": "Reference: 161cm 46kg D+27 Years #Area: Tokyo 🇯🇵 \"TG designated female child connection method\" @tk6659 💬 \"LINE connection method\" ty5563",
      "excerpt": "Looking for a date in Tokyo? Matsushima Yuyu",
      "excerptJa": "東京でデート探してる？松島悠悠",
      "excerptZh": "在東京找約會？松島悠悠",
      "date": "2024.10.25",
      "category": "日記",
      "thumbnail": "./diary/33273503cf04a5c8b678ddaa199ee48ac3ce418f.31.9.9.3.jpeg",
      "stats": null,
      "published": true
    },
    {
      "id": 27,
      "titleJa": "#日本東京 松島悠悠殿 連絡：ty5563 または telegram @tk6659",
      "titleZh": "#日本東京旅遊差異 松島悠悠殿 聯絡：ty5563 或 telegram @tk6659",
      "titleEn": "#JapanTokyoTravelingDifference Matsushima Yuyuden Sending gate: ty5563 or telegram: @tk6659",
      "contentJa": "欲望の都へようこそ 🇯🇵 あなただけの桜ラブ体験を。毎日100人以上の美女を厳選。TG @tk6659 💬 LINE ty5563",
      "contentZh": "歡迎來到慾望之都 🇯🇵 客製專屬櫻花戀愛體驗。每日精選百位美女。TG @tk6659 💬 LINE ty5563",
      "contentEn": "Welcome to the capital of desire 🇯🇵 Customize your own cherry love experience. Hundreds of beautiful women are selected every day. \"TG Designated Girl Contact\" @tk6659 💬 \"LINE Contact\" ty5563",
      "excerpt": "#JapanTokyoTravelingDifference Matsushima Yuyuden",
      "excerptJa": "#日本東京 松島悠悠殿",
      "excerptZh": "#日本東京旅遊差異 松島悠悠殿",
      "date": "2024.10.25",
      "category": "日記",
      "thumbnail": "./diary/89088e858960699637383db0c53f80289922c0d4.31.9.9.3.jpeg",
      "stats": null,
      "published": true
    }
  ]
};

if (typeof module !== 'undefined') module.exports = siteData;